### ISSUE TITLE
Update Bower underscore dependency to 1.8.3

### ISSUE THREAD

**Issue by rafde** [NYTimes/backbone.stickit#284]
Please update bower to use latest underscore, please.

**Comment by akre54** [comment]
Whups! Sorry about that, should be fixed now.

**Comment by rafde** [comment]
Nice, thanks.

**Comment by rafde** [comment]
I did a list update throught bower and the content still comeback with the `"underscore": "1.4.4 - 1.6.0"` when I did a `bower update`.

**Comment by akre54** [comment]
Try now.

**Comment by rafde** [comment]
I am still not seeing the `bower.json` file update. I could be doing something wrong.
